### ISSUE TITLE
Inquiry on the paper & code release timeline.

### ISSUE THREAD

**Issue by JiamingSuen** [hjwdzh/DeepLM#1]
Hello Jingwei @hjwdzh, this is Jiaming Sun from SenseTime & ZJU.

I came across this repo recently and found the paper title very interesting. I've been looking for a pytorch-based second-order optimizer suited for NLLS problems for a long time😁! Glad you have worked on it and got the paper accepted in CVPR, I can expect the paper to be very solid and inspiring. I'm also very interested since it can be very useful in a project I'm currently working on.

I wonder if you could give some rough timeline on the release of the paper and the code? It would be really helpful for me to plan my current project accordingly.

Thanks very much!

Best,
Jiaming Sun

**Comment by hjwdzh** [comment]
Hi Jiaming, thanks for your interest~ I just released the code. You are welcome to give me suggestions about potential directions to improve it :)
