### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by ForrestPi** [hjwdzh/DeepLM#3]
cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_CUDA=ON
-- The CXX compiler identification is GNU 8.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- The CUDA compiler identification is unknown
-- Check for working CUDA compiler: /opt/tiger/cuda/bin/nvcc
-- Check for working CUDA compiler: /opt/tiger/cuda/bin/nvcc -- broken
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCUDACompiler.cmake:46 (message):
  The CUDA compiler

    "/opt/tiger/cuda/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:
Change Dir: /opt/tiger/code/DeepLM/build/CMakeFiles/CMakeTmp

**Comment by hjwdzh** [comment]
Does it mean that the cuda toolkit is not installed properly? Can you nvcc other cuda code and run it correctly? If so, a simple solution would be "export PATH=$PATH:{Directory that contains your nvcc}", remove your cmake cache file and cmake configure again.
