### ISSUE TITLE
BACore importerror

### ISSUE THREAD

**Issue by Airplane5** [hjwdzh/DeepLM#4]
after run 
`python3 bundle_adjuster.py --balFile filename --device cpu`
there is an error:
`Traceback (most recent call last):
  File "bundle_adjuster.py", line 5, in <module>
    import BACore
ImportError: /home/wlh/DeepLM/build/BACore.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Z16THPVariable_WrapN2at6TensorE
`
ubuntu1804 without cuda

**Comment by hjwdzh** [comment]
That's probably caused by pytorch so. Try to set TORCH_USE_RTLD_GLOBAL=YES as suggested in example.sh

**Comment by Airplane5** [comment]
Sorry to reply slowly, there are many emails.
Thanks you so much, I will try it later.

**Comment by neilwang0913** [comment]
The solution does not work for me. I think the issue is still there.
